---
- name: install shell packages
  become: "{{ ansible_facts.system == 'Linux' }}"
  ansible.builtin.package:
    name: "{{ shell_packages[ansible_facts.system] }}"
    state: present

- name: install snap shell packages (linux)
  when: ansible_facts.os_family == "Debian"
  become: true
  community.general.snap:
    name: "{{ snap_packages }}"
    state: present

- name: source ~/.bashrc from ~/.bash_profile (macos)
  when: ansible_facts.system == "Darwin"
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bash_profile"
    create: true
    line: '[ -f ~/.bashrc ] && source ~/.bashrc'
    search_string: "source ~/.bashrc"
    state: present

- name: add `bashrc` function
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: function bashrc() { source "{{ rc_file }}"; }
    search_string: function bashrc(
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: add `cow` function (linux)
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: "function cow() { {{ update_cmd_linux }}; }"
    search_string: function cow(
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: add `cow` function (macos)
  when: ansible_facts.system == "Darwin"
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: "function cow() { {{ update_cmd_macos }}; }"
    search_string: function cow(
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: add `cd` aliases
  ansible.builtin.lineinfile:
    path: "{{ item.0 }}"
    create: true
    line: alias {{ item.1.alias }}='{{ item.1.cmd }}'
    search_string: alias {{ item.1.alias }}=
    state: present
  loop: "{{ rc_files | product(cd_aliases) | list }}"
  vars:
    cd_aliases:
      - { alias: '..', cmd: 'cd ..' }
      - { alias: '...', cmd: 'cd ../..' }
      - { alias: '....', cmd: 'cd ../../..' }
      - { alias: '.....', cmd: 'cd ../../../..' }

- name: alias `mkdir` to always include parents
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: alias mkdir='mkdir -p'
    search_string: alias mkdir=
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: add `where` alias
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: alias where='type -a'
    search_string: alias where=
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: display a fortune on shell open (linux)
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: "fortune | cowsay -f $(ls {{ cows_dir_linux }}/ | shuf -n1)"
    search_string: fortune | cowsay
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file

- name: display a fortune on shell open (macos)
  when: ansible_facts.system == "Darwin"
  ansible.builtin.lineinfile:
    path: "{{ rc_file }}"
    create: true
    line: "fortune | cowsay -f $(ls {{ cows_dir_macos }}/ | shuf -n1)"
    search_string: fortune | cowsay
    state: present
  loop: "{{ rc_files }}"
  loop_control:
    loop_var: rc_file
