---
- hosts: localhost
  module_defaults:
    ansible.builtin.shell:
      executable: /bin/bash
  vars:
    home: "{{ ansible_env.HOME }}"
  roles:
    - { role: bash, tags: bash }
    - { role: git, tags: git }
    - { role: sdk, tags: sdk }
