---
- name: install sdkman
  ansible.builtin.include_tasks:
    file: sdkman.yml
    apply:
      tags: sdkman
  tags: sdkman

- name: install python
  ansible.builtin.include_tasks:
    file: python.yml
    apply:
      tags: python
  tags: python

- name: (legacy) install java
  ansible.builtin.include_tasks:
    file: java.yml
    apply:
      tags: java
  tags: java
