---
- name: include python vars
  ansible.builtin.include_vars:
    file: python.yml

- name: install python versions
  become: true
  ansible.builtin.package:
    name:
      - "python{{ item }}"
      - "python{{ item }}-dev"
      - "python{{ item }}-venv"
      - "python{{ item }}-dbg"
    state: present
    update_cache: true
  loop: "{{ python_versions }}"

- name: install python alternatives
  become: true
  community.general.alternatives:
    name: python3
    path: "/usr/bin/python{{ item }}"
    link: /usr/bin/python3
    state: present
  loop: "{{ python_versions }}"

- name: select default python alternative
  become: true
  community.general.alternatives:
    name: python3
    path: "/usr/bin/python{{ default_python_version }}"
    state: selected
  when: "default_python_version | bool"

- name: remove old python versions
  become: true
  ansible.builtin.package:
    name:
      - "python{{ item }}"
      - "python{{ item }}-dev"
      - "python{{ item }}-venv"
      - "python{{ item }}-dbg"
    state: absent
  loop: "{{ remove_python_versions }}"

- name: uninstall old python alternatives
  become: true
  community.general.alternatives:
    name: python3
    path: "/usr/bin/python{{ item }}"
    link: /usr/bin/python3
    state: absent
  loop: "{{ remove_python_versions }}"
