---
- name: install git
  become: "{{ ansible_facts.system == 'Linux' }}"
  ansible.builtin.package:
    name:
      - git
      - git-crypt
      - tig
    state: present

- name: create global gitignore
  ansible.builtin.file:
    path: "{{ global_gitignore }}"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: create git scripts directory
  ansible.builtin.file:
    path: "{{ git_scripts_dir }}"
    state: directory
    mode: "0755"

- name: install git alias scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ git_scripts_dir }}/{{ item }}"
    mode: "0755"
  loop:
    - ft.sh
    - cl.sh

- name: create global git config
  ansible.builtin.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
    state: present
  loop: "{{ config | dict2items }}"
  vars:
    config:
      core.excludesfile: "{{ global_gitignore }}"
      core.whitespace: trailing-space,space-before-tab
      diff.mnemonicprefix: "true"
      feature.manyfiles: "1"
      http.postbuffer: "524288000"
      merge.stat: "true"
      mergetool.keepbackup: "false"
      pack.windowmemory: 256m
      push.default: simple
      "url.git@github.com:.insteadof": "https://github.com/"
      alias.br: branch
      alias.co: checkout
      alias.st: status
      alias.up: "!git ft && git pull && git st || git st && git pull && git st"
      alias.undo: reset --hard
      alias.df: diff --stat
      alias.wip: commit -a -m "🚧 wip"
      alias.compress: repack -a -d -f --depth=250 --window=250 --threads=12 --window-memory=256m
      alias.size: "!du -h -d 0 $(git rev-parse --show-toplevel)/.git"
      alias.maintain: "!git size && git compress && git maintenance run --auto && git gc --aggressive --prune=now && git size"
      alias.ft: "!{{ git_scripts_dir }}/ft.sh"
      alias.cl: "!{{ git_scripts_dir }}/cl.sh"

- name: append community gitignore to global gitignore
  ansible.builtin.blockinfile:
    name: "{{ global_gitignore }}"
    marker: "# {mark} ANSIBLE {{ item.name }}"
    block: "{{ lookup('url', item.url, split_lines=False) }}"
    append_newline: true
    state: present
  loop: "{{ gitignore_sources }}"

- name: create git home directory
  ansible.builtin.file:
    path: "{{ repo_root }}"
    state: directory
    mode: "0755"

- name: install paramiko for ssh_config setup
  ansible.builtin.pip:
    name: paramiko
    state: present

- name: generate ssh key
  register: keypair
  community.crypto.openssh_keypair:
    path: "{{ default_sshkey }}"
    type: ed25519
    size: 4096
    state: present

- name: add key to ssh agent
  when: keypair.changed
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add {{ default_sshkey }}

- name: work machine setup
  ansible.builtin.include_tasks:
    file: work.yml
    apply:
      tags:
        - work
  tags:
    - never
    - work
