---
- name: install git
  become: true
  ansible.builtin.package:
    name:
      - git
      - tig
    state: present

- name: create git aliases
  ansible.builtin.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
    state: present
  loop: "{{ config | dict2items }}"
  vars:
    config:
      alias.br: branch
      alias.ft: fetch --all --prune
      alias.co: checkout
      alias.st: status
      alias.undo: reset --hard
      alias.df: diff --stat
      alias.wip: commit -a -m "🚧 wip"
