---
- name: install git
  become: true
  ansible.builtin.package:
    name:
      - git
      - git-crypt
      - tig
    state: present
    update_cache: true

- name: create global gitignore
  ansible.builtin.file:
    path: "{{ global_gitignore }}"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: create global git config
  ansible.builtin.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
    state: present
  loop: "{{ config | dict2items }}"
  vars:
    config:
      core.excludesfile: "{{ global_gitignore }}"
      alias.br: branch
      alias.ft: fetch --all --prune
      alias.co: checkout
      alias.st: status
      alias.undo: reset --hard
      alias.df: diff --stat
      alias.wip: commit -a -m "🚧 wip"
      user.name: twentylemon
      user.email: "{{ email }}"

- name: append community gitignore to global gitignore
  ansible.builtin.blockinfile:
    name: "{{ global_gitignore }}"
    marker: "# {mark} ANSIBLE {{ item.name }}"
    block: "{{ lookup('url', item.url, split_lines=False) }}"
    append_newline: true
    state: present
  loop: "{{ gitignore_sources }}"

- name: create git home directory
  ansible.builtin.file:
    path: "{{ repo_root }}"
    state: directory
    mode: "0755"

- name: install paramiko for ssh_config setup
  ansible.builtin.pip:
    name: paramiko
    state: present

- name: generate ssh key
  register: keypair
  community.crypto.openssh_keypair:
    path: "{{ default_sshkey }}"
    type: ed25519
    size: 4096
    state: present

- name: add key to ssh agent
  when: keypair.changed
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add {{ default_sshkey }}

- name: work machine setup
  ansible.builtin.include_tasks:
    file: work.yml
    apply:
      tags:
        - work
  tags:
    - never
    - work
